### ISSUE TITLE
Project Tracking

### ISSUE THREAD

**Issue by becp12** [becp12/in-the-loop-v2#7]
# Project Tracking
The first feature to be added to this app is the Project Tracker.
Users need to primarily use this app to keep track of their ongoing projects (which most crafters now, this is many).
First of all, for users to be able to keep track of Projects, they need to be added to the database, this requires a mongoose schema

## Project Schema
Info to record inside every Project
- [x] User this project is linked to
```
See text snippet below, collections have games and collections are assigned to a user
```
- [x] Craft (Knit or Crochet, drop down)
- [x] Yarn
  - [x] Weight / Ply (String, text box)
  - [x] Brand (String, drop down)
  - [x] Color (String, text box)
- [x] Hook/Needle Size (Array of Objects, drop down)
eg. from ConsoleLog
```
const collectionSchema = new Schema({
    games: [{type: Schema.Types.ObjectId, ref: "Game"}],
    user: {type: Schema.Types.ObjectId, ref: "User"},
})
```
- [x] Images (Array of strings)
- [ ] Pattern (String or Object  should it reference the pattern library? Should all patterns be in library?)
- [ ] Row Counter (Clicker, + add row, - decrease row) (int)
- [x] Notes (String) (text area)

## How to display?
Having the information in the database is all well and good but it needs to be decided how these should be displayed on the screen, or else it's not useful to the using being in a database they can't access.
### Potential ideas:
On all screen a part from mobile phones, it can be a navigation bar at the top (or bottom, to replicate an app) to go to different parts of the app (upcoming features such as Yarn stash, pattern library, etc).
On Mobile phones these sections can either be navigated to, or, I can have each feature be an accordion header that is clicked to open that section. Peers have advised this could be confusing so it will require testing to see if it's hard and confusing or if users like this.
These projects will appear as tiles which will display a short version of a project and a few keys things
- [ ] Project name
- [ ] If Knit or Crochet
- [ ] Project image (first image string in array)
- [ ] Hook/Needle Size
- [ ] Row counter
If the tile is clicked on it will open and display a carousel with all the images that were uploaded as strings and all the information.
This will also include edit button and delete buttons.

## Future Ideas
In the future I may add a social feature.
In this there will be the follow extras:
- [ ] Projects can have a comment section (if their project is public)
- [ ] There will a live feed of projects being added
- [ ] Users can decide if projects are private or public
